name: Build and Release Static FFmpeg

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  IMAGE_NAME: static-ffmpeg
  BUILD_DIR: ~/build

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: arm64
            goos: linux
        variant: [ 5.0,5.1,6.0 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg FFMPEG_VERSION=${{ matrix.variant }} --output type=local,dest=${BUILD_DIR} -t ${IMAGE_NAME} .
      - name: Package Build Directory
        run: |
          tar -czvf ffmpeg-${{ matrix.variant }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz ${BUILD_DIR}
      - name: Uploading assets...
        if: ${{ !env.ACT }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ffmpeg-${{ matrix.variant }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          asset_name: ffmpeg-${{ matrix.variant }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          asset_content_type: application/gzip