name: Build and Release Static FFmpeg

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  IMAGE_NAME: static-ffmpeg
  BUILD_DIR: ~/build

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest,ubuntu-latest-arm64 ]
        version: [ '5.0','5.1','6.0' ]
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-latest-arm64
            arch: arm64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg FFMPEG_VERSION=${{ matrix.version }} --output type=local,dest=${BUILD_DIR}/ffmpeg-${{ matrix.version }} -t ${IMAGE_NAME} .
      - name: Package Build Directory
        run: |
          tar -czvf ffmpeg-${{ matrix.version }}-linux-${{ matrix.arch }}.tar.gz ${BUILD_DIR}/ffmpeg-${{ matrix.version }}
      - name: Uploading assets...
        if: ${{ !env.ACT }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ffmpeg-${{ matrix.version }}-linux-${{ matrix.arch }}.tar.gz
          asset_name: ffmpeg-${{ matrix.version }}-linux-${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip
