name: Build and Release Static FFmpeg

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  IMAGE_NAME: static-ffmpeg
  BUILD_DIR: .github
  DOCKER_BUILDKIT: 1
  CPU_ARCH: $(dpkg --print-architecture)

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest，ubuntu-latest-arm64 ]
        version: [ '5.0', '5.1', '6.0' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Package Build Directory
        run: |
          CPU_ARCH=$(dpkg --print-architecture)
          tar -czvf ffmpeg-${{ matrix.version }}-linux-${CPU_ARCH}.tar.gz ${BUILD_DIR}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffmpeg-${{ matrix.version }}-linux-${CPU_ARCH}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true